### PR TITLE
Remove eee-acpi-scripts

### PR DESCRIPTION
**Pull request by padmashree9110**
Issue : https://github.com/intel-aero/meta-intel-aero/issues/178

### CODE REVIEW

**Review by anselmolsm — CHANGES_REQUESTED** [review]
Have you verified and tested if things like the power button is still working?
#178 was about reevaluating eee-acpi-scripts, not necessarily removing them.  Please write down a few lines with the results of your evaluation and tests.

**Comment by padmashree9110** [comment]
@anselmolsm I have seen IRC chat and verified Power on/off with button before submitting PR.(forgot to add a note)
 Is there anything else that I need to verify.

**Comment by lucasdemarchi** [comment]
@padmashree9110 so... power button just works without these? Does it do a soft shutdown?

**Comment by lucasdemarchi** [comment]
then we could also probably remove these patches, too:
https://github.com/intel-aero/meta-intel-aero-base/blob/master/recipes-kernel/linux/linux-yocto/0025-intel-mid-split-keyboard-gpio-SFI-implementation-fro.patch
https://github.com/intel-aero/meta-intel-aero-base/blob/master/recipes-kernel/linux/linux-yocto/0026-input-soc_button_array-add-debounce-parameter-to-the.patch

**Comment by padmashree9110** [comment]
Yes, I verified both soft shutdown(shutdown -h now) and hard shutdown (long press power button).
I will remove those patches as well and submit another PR.

**Comment by lucasdemarchi** [comment]
> then we could also probably remove these patches, too:

ignore this. The patches would still be needed

**Comment by lucasdemarchi** [comment]
> Yes, I verified both soft shutdown(shutdown -h now) and hard shutdown (long press power button).
> I will remove those patches as well and submit another PR.

But holding the power button should trigger a soft shutdown. Is this working?

**Comment by padmashree9110** [comment]
No, by holding power button it is not triggering soft shutdown, I checked /etc/acpi/events folder, But there is no powerbtn support file which actually calls /etc/acpi/actions/power.sh script and triggers soft shutdown.

**Comment by lucasdemarchi** [comment]
So we can't simply remove that recipe yet.

**Comment by anselmolsm** [comment]
Closing this PR as we won't remove the package. Tks.

**Pull request closed without merging**
