### PR TITLE
Update aero bios version to 16

### PR DESCRIPTION
**Pull request by avinash-palleti**
Updating the bios version to 16

### CODE REVIEW

**Review by lucasdemarchi — COMMENTED** [review]
You're changing the mode, but shouldn't: 100644 → 100755

Also, what are the changes?

**Comment by avinash-palleti** [comment]
I took the rpm file from downloadcenter.intel.com and extracted it.

>Also, what are the changes?

Updates to the ACPI table for the CAN bus controller (mcp251x) connected to the Intel® Atom™ processor SPI bus, specifically configuration of the input clock and interrupt.
Updates to allow the user to read and write the Intel® Atom™ processor GPIO pins that are physically accessible through the 80-pin IO Expansion connector.

**Comment by lucasdemarchi** [comment]
> I took the rpm file from downloadcenter.intel.com and extracted it.

You forgot to chmod it to 0644 then. This is *not* an executable

> Updates to the ACPI table for the CAN bus controller (mcp251x) connected to the Intel® Atom™ processor SPI bus, specifically configuration of the input clock and interrupt.
> Updates to allow the user to read and write the Intel® Atom™ processor GPIO pins that are physically accessible through the 80-pin IO Expansion connector.

I thought all of these had been done on the previous release already. Anyway, if this is what is on their release notes, add it to the commit message.

**Comment by avinash-palleti** [comment]
> I thought all of these had been done on the previous release already.

It was released in downloadcenter and Yocto recipe was not updated.

**Comment by lucasdemarchi** [comment]
> It was released in downloadcenter and Yocto recipe was not updated.

Ahhh, ok. It is not a *new* release then.

**Pull request merged**
