### PR TITLE
kernel: Improvements in ov7251 driver

### PR DESCRIPTION
**Pull request by zehortigoza**
Increased the FPS to 75hz and added support to set exposure.
Also some minor cleanups done.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
What's the upstream status of these?

**Comment by zehortigoza** [comment]
> What's the upstream status of these?

There is no ov7251 driver in upstream, to this be send to Linux staging would be necessary to port it to the new API but I can not test it because atomisp is broken on Aero.

**Comment by zehortigoza** [comment]
@lucasdemarchi Can we merge this?

**Comment by lucasdemarchi** [comment]
I fear it will just be a maintenance burden if it's not working well.

**Comment by lucasdemarchi** [comment]
Kernel patches need sign off and it'd be good to split the cleanup from the added functionality.

**Comment by zehortigoza** [comment]
I will add the sign off.

> Kernel patches need sign off and it'd be good to split the cleanup from the added functionality.

The cleanups are in different patches.

**Comment by zehortigoza** [comment]
done

**Comment by lucasdemarchi** [comment]
Just to be clear:

`recipes-support: Add recipe to fix cameras enumeration order`

This is a short-term workaround as there's no proper way to guarantee the ordering. If user has another camera connected on USB it may not work.

Proper fix is to include libudev and filter the device you are interested in.  An udev rule to add a tag to the device may help too. You can see what properties you can check on your device by doing `udevadm info /dev/videoX`

**Pull request merged**
