### PR TITLE
intel-aero: switch to systemd-boot

### PR DESCRIPTION
**Pull request by lucasdemarchi**
Not tested yet.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
tested and it doesn't work. The same image can boot on other machines, but not on Aero. I'm guessing there's a bug on BIOS, systemd-boot, kernel or the interaction of all of them on this board.

**Comment by avinash-palleti** [comment]
@lucasdemarchi i also tried today. Same kernel works with grub-efi, so it cant be issue with kernel.
It should be issue with interaction between kernel and systemd-boot. I tried asking help in #systemd and #yocto irc channels, but no luck.

**Comment by lucasdemarchi** [comment]
@avinash-palleti AFAIK grub uses [boot protocol](https://www.kernel.org/doc/Documentation/x86/boot.txt) rather than efistub... i.e. the "bios" loads grub via efi, but then it uses the boot protocol to load the kernel. With systemd-boot the kernel **is** an efi binary that gets executed.

**Comment by avinash-palleti** [comment]
Agree. Tried same image booting on my dev setup with systemd-boot. It booted successfully.
It should be now BIOS issue. 
@anselmolsm what do you suggest next step for this issue.

**Pull request closed without merging**
